version: '3'
services:
  postgis:
    image: kartoza/postgis:latest
    container_name: postgis-geoserver
    volumes:
      - ./postgis-volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=geoserver
    ports:
      - 5432:5432
    networks:
      - geoserver
networks:
  geoserver:
    driver: bridge